name: MCCA-MEG
dependencies:
  - python=3.7.7
  - pip=20.2.3
  - numpy=1.17.2
  - scipy=1.3.1
  - matplotlib=3.1.1
  - conda-forge::mne=0.20.5
  - conda-forge::mne-bids=0.4
  - conda-forge::dicom2nifti=2.2.10
  - pandas=1.1.1
  - pip:
      -git+https://github.com/bids-standard/pybids.git

# TODO:
## Pip environment problems
