name: MCCA-MEG
dependencies:
  - python=3.7.7
  - pip=20.2.4
  - numpy=1.17.2
  - scipy=1.3.1
  - matplotlib=3.3.2
  - pandas=1.1.1
  - sklearn=0.24.0
  - conda-forge::mne=0.21.0
  - conda-forge::mne-bids=0.5 # was modified - github issues#622
  - conda-forge::dicom2nifti=2.2.10 #should be deleted if dcm2niix is successful enough
  - conda-forge::dcm2niix=1.0.20190902
  - pip:
      - pybids==0.12.3