name: MCCA-MEG
dependencies:
  - python=3.7.7
  - pip=20.2.4
  - numpy=1.17.2
  - scipy=1.3.1
  - matplotlib=3.3.2
  - conda-forge::mne=0.21.0
  - conda-forge::mne-bids=0.4
  - conda-forge::dicom2nifti=2.2.10
  - pandas=1.1.1
  - pip:
      - pybids==0.12.3